#!/usr/bin/env bash
# oneclick.sh — 一键拉取 + 自动装依赖 + 部署 + 开机自启
# 一行命令 (Ubuntu/CentOS/RHEL/macOS, 首次或更新都用同一条):
#   sh -c 'cd /tmp 2>/dev/null && (git clone -q https://github.com/cheshi888/live-player.git live-player 2>/dev/null || cd live-player && git pull -q) && cd live-player && sh oneclick.sh'
#
# 能力:
#   1. 自动检测 Node.js, 缺失时按发行版自动安装(apt/dnf/yum/brew/nvm)
#   2. 后台启动 server.js, 健康检查
#   3. Linux 下自动装 systemd 服务(开机自启 + 崩溃自动拉起)
#   4. 最终只打印: 部署成功/失败 + 访问地址 + 自启状态
set -e

REPO_NAME="live-player"
PORT="${PORT:-8090}"

# ================= 1) 定位代码目录 =================
if [ -f server.js ]; then
  git pull --ff-only >/dev/null 2>&1 || true
elif [ -d "$REPO_NAME/.git" ]; then
  cd "$REPO_NAME"; git pull --ff-only >/dev/null 2>&1 || true
fi
if [ ! -f server.js ]; then
  echo " ✗ 部署失败: 未找到 server.js (代码目录异常)"
  exit 1
fi
APP_DIR="$(pwd)"
APP_USER="$(whoami)"

# ================= 2) 检测并自动安装 Node.js =================
need_node_install=0
if ! command -v node >/dev/null 2>&1; then
  need_node_install=1
else
  NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]" 2>/dev/null || echo 0)"
  if [ "$NODE_MAJOR" -lt 18 ]; then
    need_node_install=1
  fi
fi

if [ "$need_node_install" = "1" ]; then
  echo "[setup] 未检测到 Node.js >= 18, 尝试自动安装 …"
  installed=0
  # 1. 包管理器(需 root; 非 root 则失败, 走 nvm)
  if [ "$(id -u)" = "0" ]; then
    if command -v apt-get >/dev/null 2>&1; then
      (curl -fsSL https://deb.nodesource.com/setup_20.x | bash - >/dev/null 2>&1 \
        && apt-get install -y nodejs >/dev/null 2>&1) && installed=1
    elif command -v dnf >/dev/null 2>&1; then
      (curl -fsSL https://rpm.nodesource.com/setup_20.x | bash - >/dev/null 2>&1 \
        && dnf install -y nodejs >/dev/null 2>&1) && installed=1
    elif command -v yum >/dev/null 2>&1; then
      (curl -fsSL https://rpm.nodesource.com/setup_20.x | bash - >/dev/null 2>&1 \
        && yum install -y nodejs >/dev/null 2>&1) && installed=1
    fi
  elif command -v brew >/dev/null 2>&1; then
    brew install node >/dev/null 2>&1 && installed=1
  fi
  # 2. 包管理器都不行 → 走 nvm(用户态, 无需 root)
  if [ "$installed" = "0" ]; then
    echo "[setup] 包管理器安装失败/不可用, 回退 nvm (用户态, 无需 root)"
    export NVM_DIR="$HOME/.nvm"
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash >/dev/null 2>&1
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
    nvm install 20 >/dev/null 2>&1
    nvm alias default 20 >/dev/null 2>&1
    command -v node >/dev/null 2>&1 && installed=1
  fi
  if [ "$installed" = "0" ]; then
    echo ""
    echo "=================================================="
    echo " ✗ 部署失败: 自动安装 Node.js 全部失败"
    echo "   请手动安装 Node.js >= 18 后重试: https://nodejs.org"
    echo "=================================================="
    exit 1
  fi
  # nvm 装的: 把 node 所在目录补进 PATH, 供后续 + systemd 使用
  NODE_DIR="$HOME/.nvm/versions/node/$(ls "$HOME/.nvm/versions/node" 2>/dev/null | sort -V | tail -1)"
  [ -d "$NODE_DIR/bin" ] && export PATH="$NODE_DIR/bin:$PATH"
fi
echo "[setup] Node.js $(node -v) 就绪"

# ================= 3) 停止旧实例 =================
if command -v fuser >/dev/null 2>&1; then
  fuser -k "${PORT}/tcp" >/dev/null 2>&1 || true
elif command -v lsof >/dev/null 2>&1; then
  PIDS="$(lsof -ti:"${PORT}" 2>/dev/null || true)"
  [ -n "$PIDS" ] && kill $PIDS 2>/dev/null || true
fi
sleep 1
rm -f server.pid

# ================= 4) 生成 run.sh(systemd 入口, 固化 node 路径 + PORT) =================
NODE_BIN="$(command -v node)"
cat > "$APP_DIR/run.sh" <<EOF
#!/usr/bin/env bash
# auto-generated by oneclick.sh — systemd / nohup 入口
cd "$APP_DIR"
export PORT=${PORT}
export PATH="$(dirname "$NODE_BIN"):\$PATH"
exec "$NODE_BIN" server.js
EOF
chmod +x "$APP_DIR/run.sh" 2>/dev/null || true

# ================= 5) 后台启动 + 健康检查 =================
nohup bash "$APP_DIR/run.sh" > "$APP_DIR/server.log" 2>&1 &
echo $! > "$APP_DIR/server.pid"

ok=0
i=0
while [ "$i" -lt 30 ]; do
  if curl -sf "http://127.0.0.1:${PORT}/api/status" >/dev/null 2>&1; then
    ok=1; break
  fi
  i=$((i+1)); sleep 1
done

# ================= 6) 开机自启: 优先 systemd, 降级 cron @reboot =================
systemd_msg=""

try_systemd_root(){
  # root 级 systemd 服务
  local UNIT="/etc/systemd/system/live-player.service"
  cat > "$UNIT" <<EOF
[Unit]
Description=91CG Live Player (7x24 always-on)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$APP_DIR
Environment=PORT=${PORT}
ExecStart=/bin/bash $APP_DIR/run.sh
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload >/dev/null 2>&1 || true
  if ! systemctl enable live-player.service >/dev/null 2>&1; then
    echo "[systemd] enable 失败: $(systemctl enable live-player.service 2>&1 | head -3)"
    return 1
  fi
  # 停掉手动 nohup, 交给 systemd 接管
  kill "$(cat "$APP_DIR/server.pid" 2>/dev/null)" 2>/dev/null || true
  sleep 1
  if ! systemctl start live-player.service >/dev/null 2>&1; then
    echo "[systemd] start 失败: $(systemctl start live-player.service 2>&1 | head -3)"
    echo "[systemd] journalctl: $(journalctl -u live-player.service -n 8 --no-pager 2>/dev/null | tail -6)"
    return 1
  fi
  sleep 2
  if ! systemctl is-active live-player.service >/dev/null 2>&1; then
    echo "[systemd] 服务未 active: $(systemctl status live-player.service --no-pager 2>/dev/null | head -5)"
    echo "[systemd] journalctl: $(journalctl -u live-player.service -n 10 --no-pager 2>/dev/null | tail -8)"
    return 1
  fi
  return 0
}

try_systemd_user(){
  # 非 root 走 user-level systemd(需 loginctl enable-linger 保持开机自启)
  local UNIT="$HOME/.config/systemd/user/live-player.service"
  mkdir -p "$HOME/.config/systemd/user"
  cat > "$UNIT" <<EOF
[Unit]
Description=91CG Live Player (user, 7x24 always-on)

[Service]
Type=simple
WorkingDirectory=$APP_DIR
Environment=PORT=${PORT}
ExecStart=/bin/bash $APP_DIR/run.sh
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
  systemctl --user daemon-reload >/dev/null 2>&1 || true
  systemctl --user enable --now live-player.service >/dev/null 2>&1 || true
  # 允许无登录时运行(开机自启关键)
  loginctl enable-linger "$APP_USER" >/dev/null 2>&1 || true
  sleep 2
  if systemctl --user is-active live-player.service >/dev/null 2>&1; then
    return 0
  fi
  echo "[systemd-user] 失败: $(systemctl --user status live-player.service --no-pager 2>/dev/null | head -5)"
  return 1
}

try_cron_reboot(){
  # 终极兜底: cron @reboot(无 systemd 也能开机自启)
  local CRON_LINE="@reboot /bin/bash $APP_DIR/run.sh >> $APP_DIR/server.log 2>&1"
  local EXIST
  EXIST="$(crontab -l 2>/dev/null | grep -F "live-player/run.sh" || true)"
  if [ -n "$EXIST" ]; then
    crontab -l 2>/dev/null | grep -vF "live-player/run.sh" | { crontab - 2>/dev/null || true; }
  fi
  ( crontab -l 2>/dev/null; echo "$CRON_LINE" ) | crontab - 2>/dev/null || true
  # cron 方案不能"现在"拉起, 需手动 nohup
  nohup bash "$APP_DIR/run.sh" > "$APP_DIR/server.log" 2>&1 &
  echo $! > "$APP_DIR/server.pid"
  sleep 1
  return 0
}

if [ "$(uname -s)" = "Linux" ]; then
  if command -v systemctl >/dev/null 2>&1; then
    if [ "$(id -u)" = "0" ]; then
      if try_systemd_root; then
        systemd_msg="✓ systemd(root) 服务已安装并开机自启 (systemctl status live-player)"
        # systemd 接管后重新健康检查
        ok=0; i=0
        while [ "$i" -lt 20 ]; do
          if curl -sf "http://127.0.0.1:${PORT}/api/status" >/dev/null 2>&1; then ok=1; break; fi
          i=$((i+1)); sleep 1
        done
      else
        systemd_msg="△ root systemd 失败, 尝试降级 cron @reboot"
      fi
    else
      if try_systemd_user; then
        systemd_msg="✓ systemd(user) 服务已安装并开机自启 (systemctl --user status live-player)"
        ok=0; i=0
        while [ "$i" -lt 20 ]; do
          if curl -sf "http://127.0.0.1:${PORT}/api/status" >/dev/null 2>&1; then ok=1; break; fi
          i=$((i+1)); sleep 1
        done
      else
        systemd_msg="△ user systemd 失败, 尝试降级 cron @reboot"
      fi
    fi
    # 任一 systemd 失败都再兜底 cron
    if [[ "$systemd_msg" == △* ]] && command -v crontab >/dev/null 2>&1; then
      if try_cron_reboot; then
        systemd_msg="△ systemd 不可用, 已用 cron @reboot 兜底开机自启(重启后需服务自恢复)"
      else
        systemd_msg="△ 开机自启安装失败(systemd 与 cron 都不可用), 当前仅本次运行"
      fi
    fi
  else
    # 无 systemctl(极简容器/非 systemd 系统) → cron
    if command -v crontab >/dev/null 2>&1; then
      try_cron_reboot
      systemd_msg="△ 无 systemd, 已用 cron @reboot 兜底开机自启"
    else
      systemd_msg="✗ 无法安装开机自启(无 systemd 也无 cron)"
    fi
  fi
else
  systemd_msg="△ 非 Linux ($(uname -s)), 无开机自启(重启后重跑 oneclick.sh)"
fi

# ================= 7) 干净输出: 只打印结果 + 链接 + 自启 =================
if [ "$ok" = "1" ]; then
  echo ""
  echo "=================================================="
  echo " ✓ 部署成功  (Node $(node -v), 端口 ${PORT})"
  echo ""
  echo "   访问地址:  http://localhost:${PORT}/"
  echo "   状态接口:  http://localhost:${PORT}/api/status"
  echo "   日志:      ${APP_DIR}/server.log"
  echo ""
  echo "   开机自启:  ${systemd_msg:-'非 Linux 或无 systemd (重启后可再跑一次 oneclick.sh)'}"
  if [[ "$systemd_msg" == △* || "$systemd_msg" == ✗* ]]; then
    echo ""
    echo "   --- 开机自启诊断 (Ubuntu VPS) ---"
    echo "   systemd 单元:  systemctl status live-player --no-pager"
    echo "   最近日志:      journalctl -u live-player -n 30 --no-pager"
    echo "   单元文件:      cat /etc/systemd/system/live-player.service"
    echo "   端口占用:      ss -lntp | grep ${PORT}"
    echo "   若用 cron:     crontab -l | grep live-player"
    echo "   手动验证自启:  systemctl restart live-player && systemctl is-active live-player"
  fi
  echo ""
  echo "   --- 播放诊断 (源码中断时) ---"
  echo "   单条诊断:  curl http://localhost:${PORT}/api/diag/<视频id>"
  echo "   单条自愈:  curl -X POST http://localhost:${PORT}/api/refresh?id=<视频id>"
  echo "   爬虫日志:  tail -n 40 ${APP_DIR}/server.log | grep 单条"
  echo "   状态:      curl http://localhost:${PORT}/api/status"
  echo "=================================================="
  exit 0
else
  echo ""
  echo "=================================================="
  echo " ✗ 部署失败: 30s 内未通过健康检查"
  echo "   查看日志: ${APP_DIR}/server.log"
  echo "   端口占用: ss -lntp | grep ${PORT}"
  echo "=================================================="
  tail -n 20 "$APP_DIR/server.log" 2>/dev/null || true
  exit 1
fi
